In [1]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")
# 1.1 Create a Pandas Series named 's1_1' from a list of numbers [10, 20, 30, 40, 50].
# 1.2 Create a 3x4 NumPy array named 'np_array1_2' with random integers between 1 and 100.
# 1.3 Convert 'np_array1_2' into a Pandas DataFrame named 'df1_3' with columns 'A', 'B', 'C', 'D'.

# Your code for Task 1 here:
s1_1 = pd.Series([10,20,30,40,50])
print(s1_1)

np_array1_2 = np.random.randint(1,101,size=(3,4))
print(np_array1_2)

df1_3 = pd.DataFrame(np_array1_2, columns=['A','B','C','D'])
print(df1_3)




# Task 2: Synthetic Data Generation for Practice
print("\n--- Task 2: Synthetic Data Generation for Practice ---")
# Create a DataFrame named 'df_sales' with 100 rows and the following columns:
# - 'Date': A range of dates from '2023-01-01' to '2023-04-09' (inclusive).
# - 'Region': Randomly chosen from ['East', 'West', 'North', 'South'].
# - 'Product': Randomly chosen from ['Laptop', 'Mouse', 'Keyboard', 'Monitor'].
# - 'Sales': Random integers between 100 and 1000.
# - 'Quantity': Random integers between 1 and 10.
# - Introduce 5 random NaN values in the 'Sales' column and 3 random NaN values in the 'Quantity' column.

# Your code for Task 2 here:
df_sales = pd.DataFrame({
    'Date': pd.date_range('2023-01-01','2023-04-10')[:100],
    'Region': np.random.choice(['East','West','North','South'],100),
    'Product': np.random.choice(['Laptop','Mouse','Keyboard','Monitor'],100),
    'Sales': np.random.randint(100,1001,100).astype(float),
    'Quantity': np.random.randint(1,11,100).astype(float)
})
print(df_sales.head())



# Introduce NaN values
df_sales.loc[np.random.choice(df_sales.index,5,replace=False),'Sales']=np.nan
df_sales.loc[np.random.choice(df_sales.index,3,replace=False),'Quantity']=np.nan
print(df_sales.isna().sum())




# Task 3: Indexing and Slicing in DataFrames
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")
# Use 'df_sales' from Task 2.
# 3.1 Select only the 'Region' and 'Sales' columns. Store it in 'df3_1'.
# 3.2 Select rows where 'Product' is 'Laptop'. Store it in 'df3_2'.
# 3.3 Select rows where 'Region' is 'East' AND 'Sales' are greater than 500. Store it in 'df3_3'.
# 3.4 Select the 'Sales' value for the first entry where 'Product' is 'Monitor' (use .loc and .iloc). Store it in 'val3_4'.

# Your code for Task 3 here:
df3_1=df_sales[['Region','Sales']]
print(df3_1.head())

df3_2=df_sales[df_sales['Product']=='Laptop']
print(df3_2.head())

df3_3=df_sales[(df_sales['Region']=='East')&(df_sales['Sales']>500)]
print(df3_3.head())

val3_4=df_sales.loc[df_sales['Product']=='Monitor','Sales'].iloc[0]
print(val3_4)




# Task 4: Data Cleaning (Handling Missing Values)
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")
# Use 'df_sales' from Task 2 (which should have NaNs).
# 4.1 Check how many missing values are in each column. Store the result in 'missing_counts4_1'.
# 4.2 Fill missing 'Sales' values with the mean of the 'Sales' column. Store the modified DataFrame in 'df4_2_filled'.
# 4.3 Drop rows that have any missing values in 'df_sales'. Store the result in 'df4_3_dropped'.

# Your code for Task 4 here:
missing_counts4_1=df_sales.isna().sum()
print(missing_counts4_1)

df4_2_filled=df_sales.copy()
df4_2_filled['Sales']=df4_2_filled['Sales'].fillna(df4_2_filled['Sales'].mean())
print(df4_2_filled.head())

df4_3_dropped=df_sales.dropna()
print(df4_3_dropped.head())




# Task 5: Data Manipulation (Columns, Sorting, Grouping)
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")
# Use 'df_sales' (the original one with NaNs)
# 5.1 Create a new column 'Total_Revenue' which is 'Sales' * 'Quantity'.
#     (Be mindful of NaNs, the result should also be NaN where either Sales or Quantity is NaN).
# 5.2 Sort 'df_sales' by 'Date' in ascending order, then by 'Sales' in descending order. Store it in 'df5_2_sorted'.
# 5.3 Group 'df_sales' by 'Region' and calculate the sum of 'Sales' and 'Quantity' for each region.
#     Store the result in 'df5_3_grouped_region'.
# 5.4 Group 'df_sales' by 'Product' and find the average 'Sales' for each product.
#     Store the result in 'df5_4_grouped_product'.

# Your code for Task 5 here:
df_sales['Total_Revenue']=df_sales['Sales']*df_sales['Quantity']
print(df_sales.head())

df5_2_sorted=df_sales.sort_values(by=['Date','Sales'],ascending=[True,False])
print(df5_2_sorted.head())

df5_3_grouped_region=df_sales.groupby('Region')[['Sales','Quantity']].sum()
print(df5_3_grouped_region)

df5_4_grouped_product=df_sales.groupby('Product')['Sales'].mean()
print(df5_4_grouped_product)



--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
0    10
1    20
2    30
3    40
4    50
dtype: int64
[[ 47 100  13  89]
 [ 40  92  60  28]
 [ 92  74  30  97]]
    A    B   C   D
0  47  100  13  89
1  40   92  60  28
2  92   74  30  97

--- Task 2: Synthetic Data Generation for Practice ---
        Date Region  Product  Sales  Quantity
0 2023-01-01  North   Laptop  309.0       1.0
1 2023-01-02   East   Laptop  647.0       6.0
2 2023-01-03  North  Monitor  884.0       8.0
3 2023-01-04  North    Mouse  502.0       3.0
4 2023-01-05   West    Mouse  104.0       5.0
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

--- Task 3: Indexing and Slicing in DataFrames ---
  Region  Sales
0  North  309.0
1   East  647.0
2  North  884.0
3  North    NaN
4   West  104.0
         Date Region Product  Sales  Quanti